server:
  port: 0

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  application:
    name: api-serie
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  info:
    application:
      name: api-serie

  eureka:
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

  resilience4j:
    retry:
      configs:
        default:
          max-retry-attempts: 3
          wait-duration: 1s
          retry-exceptions:
            - java.io.IOException
            - java.net.SocketTimeoutException
        instances:
          retrySerie:
            base-config: default
            max-retry-attempts: 5
            wait-duration: 2s
            retry-exceptions:
              - java.net.ConnectException
    circuitbreaker:
      configs:
        default:
          register-health-indicator: true
          sliding-window-size: 10
          minimum-number-of-calls: 5
          permitted-number-of-calls-in-half-open-state: 3
          wait-duration-in-open-state: 30s
          automatic-transition-from-open-to-half-open-enabled: true
          failure-rate-threshold: 50
      instances:
        clientSerie:
          base-config: default
          sliding-window-type: COUNT_BASED
          sliding-window-size: 5
          wait-duration-in-open-state: 1m
          failure-rate-threshold: 20
